[build]
builder= "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "/docker-entrypoint.sh uvicorn  src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType= "on_failure"
restartPolicyMaxRetries = 3